apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: daeng-map-infra
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/100-hours-a-week/20-team-daeng-ddang-cloud.git
    targetRevision: main
    path: k8s_resource
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
