# be-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: be-secret
type: Opaque
stringData:
  DB_PASSWORD: "<DB 비밀번호>"
  KAKAO_REST_API_KEY: "<카카오 REST API 키>"
  KAKAO_CLIENT_ID: "<카카오 클라이언트 ID>"
  KAKAO_CLIENT_SECRET: "<카카오 클라이언트 시크릿>"
  KAKAO_ADMIN_KEY: "<카카오 어드민 키>"
  JWT_SECRET: "<JWT 시크릿 키(Base64 인코딩)>"
  AWS_ACCESS_KEY_ID: "<AWS 액세스 키 ID>"
  AWS_SECRET_ACCESS_KEY: "<AWS 시크릿 액세스 키>"