nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  repository: daengmap/daeng-map-frontend
  tag: abdc652ff70901b121fe2e3c016717b2a4eb24d8
  pullPolicy: IfNotPresent

serviceAccount:
  name: frontend-sa

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

containerPort: 3000

resources:
  requests:
    cpu: "500m"
    memory: "250Mi"
  limits:
    cpu: "1500m"
    memory: "500Mi"

env:
  PORT: "3000"
  NODE_ENV: production

secretRefName: frontend-secret

readinessProbe:
  enabled: true
  path: /healthcheck
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 3

livenessProbe:
  enabled: true
  path: /healthcheck
  initialDelaySeconds: 30
  periodSeconds: 15
  timeoutSeconds: 3
  failureThreshold: 3

